### PR TITLE
Tweak index page

### PR DESCRIPTION
**Pull request by stefanbuck**
# Preview

screen shot 2018-01-02 at 21 47 32

### CODE REVIEW

**Comment by josephfrazier** [comment]
LGTM! I realized that using Heroku's [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) might be a good way to easily preview/test changes in PRs. What do you think about enabling those?

**Comment by stefanbuck** [comment]
In general a good idea. I'm just a bit worried about the unknown costs. What if someone creates 100+ PRs. 

> Review apps are charged as any other app you might create. 

Do you know if we can restrict / limit review apps?

**Comment by josephfrazier** [comment]
Even if automatic review apps are enabled, they're only created for PRs of branches in *this* repo, not forks:

> For security and billing reasons, Heroku will not automatically create review apps for pull requests to public repos that are sent from forks. Review apps can still be created manually for these pull requests.

**Comment by stefanbuck** [comment]
Good to know. Let's do it. Will configure it later this week. Thanks for the suggestion.

**Pull request merged**
