### PR TITLE
Changes required to use Hapi 17

### LINKED ISSUE #51: Upgrade hapijs
In Hapi 17 the entire api has moved away from callbacks and toward async/await. This is really great, but makes migrating a little bit harder. They provide a migration checklist so it's shouldn't be that complicated, hopefully just a little time consuming 🤞 

https://github.com/hapijs/hapi/issues/3658

### PR DESCRIPTION
**Pull request by stefanbuck**
As you might have noticed, Hapi with version 17 has recently moved to using async/await. This requires breaking changes. Luckily it was quite simple in our case. All Hapi related dependencies have also been updated to the latest versions.

Fix #51

### CODE REVIEW

**Comment by stefanbuck** [comment]
I see  some random failing tests on my machine ... we should hold this back until I figured out why this is happening.

**Comment by josephfrazier** [comment]
Are the tests still failing for you? I wasn't able to reproduce the failures on my machine. If they're just timeouts from third-party servers randomly being slow, I don't think it's worth worrying about.

**Comment by stefanbuck** [comment]
You're right, it's just about third-party servers being slow. After increasing the timeout it works all the time. Thanks for the hint

**Comment by josephfrazier** [comment]
Good to hear! This looks great to me, I'm glad to see the async/await interface rather than callbacks. Feel free to merge if there's nothing else to do!

**Pull request merged**
